// Create tables
POST http://localhost:3000/week12-1/api/tables

###

###

// Create user
POST http://localhost:3000/week12-1/api/users HTTP/1.1
content-type: application/json

{
    "name": "Abe",
    "age": 20
}

###

// Create user
POST http://localhost:3000/week12-1/api/users HTTP/1.1
content-type: application/json

{
    "name": "Bob",
    "age": 30
}

###

// Create user
POST http://localhost:3000/week12-1/api/users HTTP/1.1
content-type: application/json

{
    "name": "Carl",
    "age": 25
}

###

// Create users
GET http://localhost:3000/week12-1/api/users

###

// Get user by id
GET http://localhost:3000/week12-1/api/users/9

###

// Replace user by id
PUT http://localhost:3000/week12-1/api/users/9 HTTP/1.1
content-type: application/json

{
    "name": "Bobby",
    "age": 31
}

###

// Update user by id
PATCH http://localhost:3000/week12-1/api/users/9 HTTP/1.1
content-type: application/json

{
    "name": "Bob Bobberson"
}

###

// Delete user by id
DELETE http://localhost:3000/week12-1/api/users/9 HTTP/1.1

###

// Delete all users
DELETE http://localhost:3000/week12-1/api/users HTTP/1.1

###

// Drop all tables. You can use this to reset the database.
DELETE http://localhost:3000/week12-1/api/tables HTTP/1.1
